### ISSUE TITLE
Disable watching in ember build

### ISSUE THREAD

**Issue by Gaurav0** [typed-ember/ember-cli-typescript#236]
Getting the following error in ci while building for deployment (`ember build --environment=production`):

Error: watch /opt/ember_app ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/opt/ember_app/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/opt/ember_app/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/opt/ember_app/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/opt/ember_app/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/opt/ember_app/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/opt/ember_app/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

I think we shouldn't be watching files unless we are using `ember build --watch` or `ember serve`.

Upgrading from 1.3.2 to latest master (f3ab41a2fb29c6c4135e94718d160fa06ac6f7a3) does not fix the error.

**Comment by chriskrycho** [comment]
@Gaurav0 sorry about the long delay; I somehow missed this back when it was opened. I'm closing this as there's a reason we run a file watcher in the 1.x series (having to do with the gnarly dance we make TS do there). However, this will also be fixed in the 2.0.0 release, because we were able to eliminate that dance by way of Babel's new TS support.
