### ISSUE TITLE
Incompatibility with ember-cli-emblem: property 'moduleName' undefined

### ISSUE THREAD

**Issue by leepfrog** [typed-ember/ember-cli-typescript#592]
### Please paste the output of `ember -v` here
ember-cli: 3.7.1
node: 10.15.1
os: darwin x64

### Please paste the output of `tsc -v` here
Version 3.3.3

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
ember g route foo # Note that route is created
ember install ember-cli-emblem
ember g route bar # Note that exception is thrown
Cannot read property 'moduleName' of undefined


Stack Trace and Error Report: /var/folders/jb/_4w1sdcn74582tchhlkbyxnh0000gp/T/error.dump.2bf32216bfdad884fb87a8bda317717a.log
```

**Comment by leepfrog** [comment]
Might be related to #165

**Comment by leepfrog** [comment]
Stack trace:

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'moduleName' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'moduleName' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'moduleName' of undefined
    at __name__ (/Users/leepfrog/Development/web/sample/node_modules/ember-cli-typescript-blueprints/blueprints/route/index.js:35:31)
    at fileMapValues.map.token (/Users/leepfrog/Development/web/sample/node_modules/ember-cli/lib/models/blueprint.js:651:50)
    at Array.map (<anonymous>)
    at Class.generateFileMap (/Users/leepfrog/Development/web/sample/node_modules/ember-cli/lib/models/blueprint.js:651:37)
    at Promise.then.customLocals (/Users/leepfrog/Development/web/sample/node_modules/ember-cli/lib/models/blueprint.js:848:26)
    at tryCatcher (/Users/leepfrog/Development/web/sample/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/leepfrog/Development/web/sample/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/leepfrog/Development/web/sample/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/leepfrog/Development/web/sample/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by chriskrycho** [comment]
@leepfrog just getting back to this – not sure what the issue is for sure, but wanted to let you know we've seen it and one of us will circle back to it soon!
